site_name: Mail Attachments
repo_url: https://github.com/systopia/de.systopia.mailattachment
site_description: 'A guide for the Mail Attachments extension.'
site_author: 'SYSTOPIA'
theme:
  name:
    material

nav:
  - Home: index.md
  - Attachment Types: attachment-types.md
  - Installation: installation.md
  - Usage: usage.md
  - Developer Information: developer-information.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
