site_name: Mail Attachments
site_description: 'A guide for the Mail Attachments extension.'
site_author: SYSTOPIA
site_url: https://github.com/systopia/de.systopia.mailattachment

theme:
  name: material

nav:
  - Introduction: index.md
  - Attachment Types: attachment-types.md
  - Installation: installation.md
  - Usage: usage.md
  - Developer Information: developer-information.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
